BEGIN;

SET CLIENT_ENCODING TO 'UTF-8';

DROP TABLE IF EXISTS "user", "website", "comment";

CREATE TABLE "user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" TEXT UNIQUE NOT NULL,
  "hash" TEXT NOT NULL
);

CREATE TABLE "website" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "slug" TEXT NOT NULL UNIQUE,
  "title" TEXT NOT NULL,
  "description" TEXT,
  "address" TEXT NOT NULL,
  "device" TEXT,
  "level" TEXT,
  "user_id" INTEGER REFERENCES "user"("id"),
  "image" TEXT
);


CREATE TABLE "comment" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" TEXT NOT NULL,
  "user_id" INTEGER REFERENCES "user"("id"),
  "website_id" INTEGER REFERENCES "website"("id"),
  "date_added" DATE DEFAULT CURRENT_DATE
);


COMMIT;
