services:
  web:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://testpilori:testpilori@postgres:5432/testpilori
    # volumes:
    #   - ./app/.env:/app/.env
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: testpilori
      POSTGRES_PASSWORD: testpilori
      POSTGRES_DB: testpilori
    # ports:
    #   - "5432:5432"
